### ISSUE TITLE
Issues using Ubuntu

### ISSUE THREAD

**Issue by nubbix** [markruys/scandns#1]
Error message 

Can't locate Net/Netmask.pm in @INC (you may need to install the Net::Netmask module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at scandns.pl line 27.
BEGIN failed--compilation aborted at scandns.pl line 27.

**Comment by markruys** [comment]
Indeed you have to install Net::Netmask first as do program depends on it.

**Comment by nubbix** [comment]
Thank you, that fixed it :)
Excellent program
